language: node_js
node_js:
  - "9"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
        
before_script:
  - npm install
  - npm install -g nightwatch

script:
  - npm test test/e2e/Pavlov_hVharassment.js

notifications:
  email: false  